%YAML 1.2

scheduler:
  num_decompress_ops: 3
  worker_threads: 4

image_src:
  zmq_endpoint: "tcp://172.23.82.48:31001"
  receive_timeout_ms: 100
  batch_size: 1000

decompress_op:
  data_size: [514, 1030]
  data_dtype: uint16

position_src:
  #zmq_endpoint: "tcp://bl13j-ea-serv-02:6666"
  zmq_endpoint: "tcp://172.23.82.204:6666"
  receive_timeout_ms: 1000

masking_op:
  center_x: 257
  center_y: 515
  radius: 128

sink_and_publish_op:
  publish_tensors: ["positions", "positions_ids", "inner", "outer", "intensity_ids"]
  # publish_folder: null
  publish_folder: "./processed"
  temp_folder: "./temp"
  backend: "zmq"  # Options: "nats" or "zmq"
  backend_endpoint: "tcp://localhost:6010"  # ZMQ endpoint or NATS host:port
  # backend: "nats"  # Options: "nats" or "zmq"
  # backend_endpoint: "localhost:6000"  # ZMQ endpoint or NATS host:port
  
